# Generated by Django 5.2.4 on 2025-07-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('borrower_name', models.CharField(max_length=100)),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Borrowed Library Book',
                'verbose_name_plural': 'Borrowed Library Books',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
